Sprint 6 solution: add unlimited and sorted history
sosnin-ivan/java-kanban pull request #1
Opened 2024-08-05 00:16 UTC by sosnin-ivan

2024-08-05 09:30 UTC, YazykovMikhail requested changes

2024-08-05 09:30 UTC, YazykovMikhail commented on src/ru/yandex/javacource/sosnin/schedule/manager/InMemoryHistoryManager.java
> +    public void remove(int id) {
Отлично, можно еще улучшить вот так:
```
	public void remove(int id) {
		final Node node = history.remove(id);
		if (node == null) {
			return;
		}
		removeNode(node);
	}
```

2024-08-05 09:30 UTC, YazykovMikhail commented on src/ru/yandex/javacource/sosnin/schedule/manager/InMemoryHistoryManager.java
> +        if (history.containsKey(task.getId())) {
Старайся избегать двойных поисков, сначала провеярешь, потом получаешь в итоге двойной поиск. 
И так же нет удаления старой версии задачи, как скзаано в заднии должна быть только последняя, так что тут можно просто:
`remove(task.getId();`
Вызвать уже готовый метод

2024-08-05 09:30 UTC, YazykovMikhail commented on src/ru/yandex/javacource/sosnin/schedule/manager/InMemoryHistoryManager.java
> +        Node node = new Node(task);
отправь создание Node в метод linkLast, все таки он отвечает за ностйроку Ноды и ее положения

2024-08-05 09:30 UTC, YazykovMikhail commented on src/ru/yandex/javacource/sosnin/schedule/manager/InMemoryHistoryManager.java
> +        history.put(task.getId(), node);
После того как отправишь созадние Node в метод linkLast тут будет:
history.put(id, tail);

2024-08-06 07:28 UTC, YazykovMikhail approved these changes

2024-08-06 07:28 UTC, YazykovMikhail commented on src/ru/yandex/javacource/sosnin/schedule/manager/InMemoryHistoryManager.java
> +        if (history.containsKey(id)) {
Как писал в предыдущем ревью, эта проверка не нужно, ведь она уже есть в методе remove
Просто вызывай метод remove
(Посмотри предыдущий комментарий в этом месте)

2024-08-06 09:11 UTC, sosnin-ivan commented on src/ru/yandex/javacource/sosnin/schedule/manager/InMemoryHistoryManager.java
> +        if (history.containsKey(id)) {
аа, дошло! недопонял в прошлый раз, исправляю)

2024-08-06 09:13 UTC, merged